modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"

[[mods]]
modId="more_effects_in_potions"
version="1.0.0"
displayName="More Effects in Potions"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="break08"
description="Add more potions with vanilla effects that can't be crafted"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.more_effects_in_potions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration